#include "projectile/kalman_tracker.hpp"
#include "projectile/hungarian.hpp"
#include <algorithm>
#include <cmath>
namespace projectile {
KalmanTracker::KalmanTracker(const Config& c):config_(c){}
static cv::KalmanFilter make_filter(const cv::Point2f& p){cv::KalmanFilter k(4,2,0,CV_32F);k.transitionMatrix=(cv::Mat_<float>(4,4)<<1,0,1,0,0,1,0,1,0,0,1,0,0,0,0,1);k.measurementMatrix=(cv::Mat_<float>(2,4)<<1,0,0,0,0,1,0,0);k.processNoiseCov=cv::Mat::eye(4,4,CV_32F)*.01F;k.processNoiseCov.at<float>(2,2)=.05F;k.processNoiseCov.at<float>(3,3)=.05F;k.measurementNoiseCov=cv::Mat::eye(2,2,CV_32F);k.errorCovPost=cv::Mat::eye(4,4,CV_32F);k.statePre=(cv::Mat_<float>(4,1)<<p.x,p.y,0,0);k.statePost=k.statePre;return k;}
std::vector<Track> KalmanTracker::update(const std::vector<Detection>& ds){std::vector<cv::Point2f> predictions;for(auto& s:states_){auto p=s.filter.predict();predictions.push_back({p.at<float>(0),p.at<float>(1)});++s.age;}std::vector<std::vector<double>> cost(states_.size(),std::vector<double>(ds.size()));for(size_t i=0;i<states_.size();++i)for(size_t j=0;j<ds.size();++j)cost[i][j]=cv::norm(predictions[i]-ds[j].center);std::vector<bool> mt(states_.size()),md(ds.size());for(auto [r,c]:hungarian(cost))if(cost[r][c]<=config_.kalman_max_distance){auto& s=states_[r];s.filter.correct((cv::Mat_<float>(2,1)<<ds[c].center.x,ds[c].center.y));s.detection=ds[c];s.missing=0;s.predicted=false;s.innovation=cost[r][c];mt[r]=md[c]=true;}for(size_t i=0;i<states_.size();++i)if(!mt[i]){++states_[i].missing;states_[i].predicted=true;}for(size_t j=0;j<ds.size();++j)if(!md[j]){State s; s.id=next_id_++;s.filter=make_filter(ds[j].center);s.detection=ds[j];states_.push_back(std::move(s));}states_.erase(std::remove_if(states_.begin(),states_.end(),[&](const State& s){return s.missing>config_.kalman_max_missing;}),states_.end());std::vector<Track> out;for(auto& s:states_){auto st=s.filter.statePost;Track t;t.id=s.id;t.center={st.at<float>(0),st.at<float>(1)};t.velocity={st.at<float>(2),st.at<float>(3)};t.speed=cv::norm(t.velocity);t.age=s.age;t.missing=s.missing;t.predicted=s.predicted;t.innovation=s.innovation;t.detection=s.detection;t.box=s.detection?s.detection->box:BoundingBox{int(t.center.x)-4,int(t.center.y)-4,8,8};out.push_back(t);}return out;}
void KalmanTracker::reset(){states_.clear();next_id_=0;}
}
